name: Scrape

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"

env:
  ENV DEBIAN_FRONTEND: noninteractive
  TLP_URL: https://trustee.ietf.org/assets/licenses/license-for-open-source-repositories/
  TLP_START: "^Official boilerplate text:"
  TLP_END: "^Search for:"
  NOTEWELL_URL: https://www.ietf.org/about/note-well/
  NOTEWELL_START: "^A reminder of IETF policies."
  NOTEWELL_END: "^About"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get -y install --no-install-recommends w3m pandoc
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Scrape TLP
        run: |
          w3m -cols 999999 -dump $TLP_URL |
            sed -E -e "1,/$TLP_START/d; /$TLP_END/,\$d" > /tmp/tlp.txt
          sed -E -e "s|\s+| |g" \
                 -e "s|http:|https:|g" \
                 -e "s|e.g. |e.g., |g" \
                 -e "s|policies of IETF|policies of the IETF|g" \
                 -e "s|Simplified BSD|Revised BSD|g" \
                 -e "s|(IETF Trust Legal Provisions \(TLP\) Relating to IETF Documents) \(|[\1](|g" \
                 -e "s|(IETF Standards Process) \(|[\1](|g" \
                 -e "s|(BCP [0-9]+) \(|[\1](|g" \
                 -e "s|www.ietf.org/|www.rfc-editor.org/info/bcp9|g" \
                 -e "s|(Internet Engineering Task Force \(IETF\))|[\1](\https://www.ietf.org/)|g" /tmp/tlp.txt |
            sed -E -e "1s/^/# License\n/" |
            pandoc -f markdown -t gfm > LICENSE.md
            cat LICENSE.md
      - name: Scrape Note Well
        run: |
          w3m -cols 999999 -dump $NOTEWELL_URL |
            sed -E -e "1,/$NOTEWELL_START/d; /$NOTEWELL_END/,\$d" > /tmp/notewell.txt
          cat /tmp/notewell.txt
          sed -E -e "s|\s+| |g" \
                 -e "s|(ombudsteam) \(|[\1](|g" \
                 -e "s|BCP ([0-9+])|[BCP \1](https://www.rfc-editor.org/info/bcp\1)|g" \
                 -e "s|https://www.ietf.org/privacy-policy/.*|[Privacy Policy](https://www.ietf.org/privacy-policy/)|g" \
                 -e "s|\s+•|*|g" /tmp/notewell.txt |
            sed -E -e "1s/^/# Note Well\n/" > NOTE-WELL.md
            cat NOTE-WELL.md
            pandoc -f markdown -t gfm NOTE-WELL.md
      - name: Check diff
        run: git diff

      # - name: Send mail
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: ${{secrets.MAIL_USERNAME}}
      #     password: ${{secrets.MAIL_PASSWORD}}
      #     subject: Latest PPRA tenders for ${{env.DATE}}
      #     to: hi@yasoob.me
      #     from: Automated Email
      #     ignore_cert: true
      #     secure: true
      #     html_body: file://ppra.html
