name: Scrape

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"

env:
  ENV DEBIAN_FRONTEND: noninteractive
  TLP_URL: https://trustee.ietf.org/assets/licenses/license-for-open-source-repositories/
  TLP_START: "^Official boilerplate text:"
  TLP_END: "^Search for:"

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get -y install --no-install-recommends w3m
      - name: Scrape TLP
        run: |
          w3m -cols 999999 -dump $TLP_URL > tlp.txt |
            sed -E -e "1,/$TLP_START/d; /$TLP_END/,\$d" > tlp.txt
          sed -E -e "s/http:/https:/g" \
                 -e "s/e.g. /e.g., /g" \
                 -e "s/policies of IETF/policies of the IETF/g" \
                 -e "s/Simplified BSD/Revised BSD/g" \
                 -e "s/(IETF Trust Legal Provisions \(TLP\) Relating to IETF Documents) \(/[\1]\(/g" \
                 -e "s/(IETF Standards Process) \(/[\1]\(/g" \
                 -e "s/(BCP [0-9]+) \(/[\1]\(/g" tlp.txt |
            sed -E -e "1s/^/# License\n/" |
            fmt -w 72 > tlp.md
          cat tlp.md
          diff -u tlp.txt tlp.md

      # - name: Send mail
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: ${{secrets.MAIL_USERNAME}}
      #     password: ${{secrets.MAIL_PASSWORD}}
      #     subject: Latest PPRA tenders for ${{env.DATE}}
      #     to: hi@yasoob.me
      #     from: Automated Email
      #     ignore_cert: true
      #     secure: true
      #     html_body: file://ppra.html
