name: Scrape

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"

env:
  ENV DEBIAN_FRONTEND: noninteractive
  TLP_URL: https://trustee.ietf.org/assets/licenses/license-for-open-source-repositories/
  TLP_START: "^Official boilerplate text:"
  TLP_END: "^Search for:"

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get -y install --no-install-recommends w3m
      - name: Scrape TLP
        run: |
          w3m -cols 999999 -dump $TLP_URL > tlp.txt
          sed -i "1,/$TLP_START/d; /$TLP_END/,\$d" > tlp.txt
          fmt -n -s -w 72 tlp.txt
          cat tlp.txt
      # - name: Send mail
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: ${{secrets.MAIL_USERNAME}}
      #     password: ${{secrets.MAIL_PASSWORD}}
      #     subject: Latest PPRA tenders for ${{env.DATE}}
      #     to: hi@yasoob.me
      #     from: Automated Email
      #     ignore_cert: true
      #     secure: true
      #     html_body: file://ppra.html
